### ISSUE TITLE
All tickets subject revealed: $clientsdetails not included in WHMCS 6.2.2

### ISSUE THREAD

**Issue by hvdolf** [kayako/whmcs-integration#43]
After update whmcs to version 6.2.2 the $clientsdetails is not present in support module and there is no validation of $clientsdetails['email'] in several files like: supporttickets.php, submitticket.php.

- (Huge Bug) all tickets subject were display in every whmcs client account as $clientsdetails['email'] is not set.
- ticket submit fail because required $clientsdetails['email'] not present.

The only place were $clientsdetails['email'] is validated is in viewticket.php and that stop the display of not owned tickets.

**Comment by mansiwason** [comment]
Hi,
Yes, you are correct. We are aware of the changes done with the new update of whmcs 6.2.2 that makes our app is little unsecure. So, we have fixed this issue in our app.

We also have reported the same problem to WHMCS and confirmed this (missing $clientsdetails) as a defect and they will be releasing the new build soon.

So, I would recommend you to please create a ticket on support.kayako.com so that we can help you with the patch and makes your integration compatible to the latest version.

Thanks and Regards,
Mansi Wason

**Comment by hvdolf** [comment]
Hi,
We write a custom patch on the fly to overcome this. I'm going to submit a ticket for the official patch release. Thank you.
